//***************************************
//IDR home page: http://kpnc.org/idr32/en
//Decompiled by IDR v.01.04.2017
//***************************************
unit _Unit116;

interface

uses
  SysUtils, Classes;

type
  TWPMSiteMap = class(TObject)
    constructor Create;//00614FC8
  end;
    procedure sub_00615080(?:TWPMSiteMap);//00615080
    procedure sub_00615540(?:TWPMSiteMap; ?:AnsiString);//00615540

implementation

//00614FC8
constructor TWPMSiteMap.Create;
begin
{*
 00614FC8    push        ebp
 00614FC9    mov         ebp,esp
 00614FCB    push        ecx
 00614FCC    push        ebx
 00614FCD    push        esi
 00614FCE    test        dl,dl
>00614FD0    je          00614FDA
 00614FD2    add         esp,0FFFFFFF0
 00614FD5    call        @ClassCreate
 00614FDA    mov         byte ptr [ebp-1],dl
 00614FDD    mov         esi,eax
 00614FDF    mov         dword ptr [esi+8],ecx
 00614FE2    mov         dl,1
 00614FE4    mov         eax,[0041B4BC];TStringList
 00614FE9    call        TObject.Create;TStringList.Create
 00614FEE    mov         ebx,eax
 00614FF0    mov         dword ptr [esi+4],ebx
 00614FF3    mov         eax,ebx
 00614FF5    mov         edx,615028;'<?xml version="1.0" encoding="UTF-8" ?>'
 00614FFA    mov         ecx,dword ptr [eax]
 00614FFC    call        dword ptr [ecx+38];TStringList.Add
 00614FFF    mov         eax,esi
 00615001    cmp         byte ptr [ebp-1],0
>00615005    je          00615016
 00615007    call        @AfterConstruction
 0061500C    pop         dword ptr fs:[0]
 00615013    add         esp,0C
 00615016    mov         eax,esi
 00615018    pop         esi
 00615019    pop         ebx
 0061501A    pop         ecx
 0061501B    pop         ebp
 0061501C    ret
*}
end;

//00615080
procedure sub_00615080(?:TWPMSiteMap);
begin
{*
 00615080    push        ebp
 00615081    mov         ebp,esp
 00615083    mov         ecx,6
 00615088    push        0
 0061508A    push        0
 0061508C    dec         ecx
>0061508D    jne         00615088
 0061508F    push        ebx
 00615090    push        esi
 00615091    push        edi
 00615092    mov         esi,eax
 00615094    xor         eax,eax
 00615096    push        ebp
 00615097    push        6152B5
 0061509C    push        dword ptr fs:[eax]
 0061509F    mov         dword ptr fs:[eax],esp
 006150A2    lea         edx,[ebp-8]
 006150A5    mov         eax,dword ptr [esi+8]
 006150A8    call        00617F24
 006150AD    lea         edx,[ebp-10]
 006150B0    mov         eax,dword ptr [ebp-8]
 006150B3    call        0048DD90
 006150B8    mov         edx,dword ptr [ebp-10]
 006150BB    lea         eax,[ebp-8]
 006150BE    call        @LStrLAsg
 006150C3    mov         edx,6152CC;'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http:...
 006150C8    mov         eax,dword ptr [esi+4]
 006150CB    mov         ecx,dword ptr [eax]
 006150CD    call        dword ptr [ecx+38]
 006150D0    mov         edx,6153C0;'<!--  Generated by Web Page Maker from http://www.webpage-maker.com  -->'
 006150D5    mov         eax,dword ptr [esi+4]
 006150D8    mov         ecx,dword ptr [eax]
 006150DA    call        dword ptr [ecx+38]
 006150DD    mov         eax,dword ptr [esi+8]
 006150E0    call        00616570
 006150E5    mov         edi,eax
 006150E7    dec         edi
 006150E8    test        edi,edi
>006150EA    jl          0061528D
 006150F0    inc         edi
 006150F1    mov         dword ptr [ebp-4],0
 006150F8    mov         edx,dword ptr [ebp-4]
 006150FB    mov         eax,dword ptr [esi+8]
 006150FE    call        00616578
 00615103    mov         edx,dword ptr ds:[607B2C];TXMLWebPage
 00615109    call        @AsClass
 0061510E    mov         ebx,eax
 00615110    mov         edx,615414;'<url>'
 00615115    mov         eax,dword ptr [esi+4]
 00615118    mov         ecx,dword ptr [eax]
 0061511A    call        dword ptr [ecx+38]
 0061511D    push        615424;'<loc>'
 00615122    push        dword ptr [ebp-8]
 00615125    lea         edx,[ebp-18]
 00615128    mov         eax,ebx
 0061512A    call        006091EC
 0061512F    push        dword ptr [ebp-18]
 00615132    lea         edx,[ebp-1C]
 00615135    mov         eax,ebx
 00615137    call        00609234
 0061513C    push        dword ptr [ebp-1C]
 0061513F    push        615434;'</loc>'
 00615144    lea         eax,[ebp-14]
 00615147    mov         edx,5
 0061514C    call        @LStrCatN
 00615151    mov         edx,dword ptr [ebp-14]
 00615154    mov         eax,dword ptr [esi+4]
 00615157    mov         ecx,dword ptr [eax]
 00615159    call        dword ptr [ecx+38]
 0061515C    lea         ecx,[ebp-20]
 0061515F    mov         edx,615444;'lastmod'
 00615164    mov         eax,ebx
 00615166    call        006086B4
 0061516B    cmp         dword ptr [ebp-20],0
>0061516F    je          0061517C
 00615171    mov         eax,ebx
 00615173    call        006129BC
 00615178    test        al,al
>0061517A    je          00615197
 0061517C    call        Date
 00615181    add         esp,0FFFFFFF8
 00615184    fstp        qword ptr [esp]
 00615187    wait
 00615188    lea         edx,[ebp-0C]
 0061518B    mov         eax,615454;'YYYY-MM-DD'
 00615190    call        FormatDateTime
>00615195    jmp         006151A6
 00615197    lea         ecx,[ebp-0C]
 0061519A    mov         edx,615444;'lastmod'
 0061519F    mov         eax,ebx
 006151A1    call        006086B4
 006151A6    push        615468;'<lastmod>'
 006151AB    push        dword ptr [ebp-0C]
 006151AE    push        61547C;'</lastmod>'
 006151B3    lea         eax,[ebp-24]
 006151B6    mov         edx,3
 006151BB    call        @LStrCatN
 006151C0    mov         edx,dword ptr [ebp-24]
 006151C3    mov         eax,dword ptr [esi+4]
 006151C6    mov         ecx,dword ptr [eax]
 006151C8    call        dword ptr [ecx+38]
 006151CB    mov         edx,615490;'Freq'
 006151D0    mov         eax,ebx
 006151D2    call        006086DC
 006151D7    test        eax,eax
>006151D9    je          00615212
 006151DB    push        6154A0;'<changefreq>'
 006151E0    mov         edx,615490;'Freq'
 006151E5    mov         eax,ebx
 006151E7    call        006086DC
 006151EC    mov         edx,dword ptr ds:[72536C];^gvar_0070C1A8:array[8] of ?
 006151F2    push        dword ptr [edx+eax*4]
 006151F5    push        6154B8;'</changefreq>'
 006151FA    lea         eax,[ebp-28]
 006151FD    mov         edx,3
 00615202    call        @LStrCatN
 00615207    mov         edx,dword ptr [ebp-28]
 0061520A    mov         eax,dword ptr [esi+4]
 0061520D    mov         ecx,dword ptr [eax]
 0061520F    call        dword ptr [ecx+38]
 00615212    mov         edx,6154D0;'Priority'
 00615217    mov         eax,ebx
 00615219    call        006086DC
 0061521E    cmp         eax,0A
>00615221    jne         00615232
 00615223    lea         eax,[ebp-0C]
 00615226    mov         edx,6154E4;'1.0'
 0061522B    call        @LStrLAsg
>00615230    jmp         00615251
 00615232    lea         ecx,[ebp-2C]
 00615235    mov         edx,6154D0;'Priority'
 0061523A    mov         eax,ebx
 0061523C    call        006086B4
 00615241    mov         ecx,dword ptr [ebp-2C]
 00615244    lea         eax,[ebp-0C]
 00615247    mov         edx,6154F0;'0.'
 0061524C    call        @LStrCat3
 00615251    push        6154FC;'<priority>'
 00615256    push        dword ptr [ebp-0C]
 00615259    push        615510;'</priority>'
 0061525E    lea         eax,[ebp-30]
 00615261    mov         edx,3
 00615266    call        @LStrCatN
 0061526B    mov         edx,dword ptr [ebp-30]
 0061526E    mov         eax,dword ptr [esi+4]
 00615271    mov         ecx,dword ptr [eax]
 00615273    call        dword ptr [ecx+38]
 00615276    mov         edx,615524;'</url>'
 0061527B    mov         eax,dword ptr [esi+4]
 0061527E    mov         ecx,dword ptr [eax]
 00615280    call        dword ptr [ecx+38]
 00615283    inc         dword ptr [ebp-4]
 00615286    dec         edi
>00615287    jne         006150F8
 0061528D    mov         edx,615534;'</urlset>'
 00615292    mov         eax,dword ptr [esi+4]
 00615295    mov         ecx,dword ptr [eax]
 00615297    call        dword ptr [ecx+38]
 0061529A    xor         eax,eax
 0061529C    pop         edx
 0061529D    pop         ecx
 0061529E    pop         ecx
 0061529F    mov         dword ptr fs:[eax],edx
 006152A2    push        6152BC
 006152A7    lea         eax,[ebp-30]
 006152AA    mov         edx,0B
 006152AF    call        @LStrArrayClr
 006152B4    ret
>006152B5    jmp         @HandleFinally
>006152BA    jmp         006152A7
 006152BC    pop         edi
 006152BD    pop         esi
 006152BE    pop         ebx
 006152BF    mov         esp,ebp
 006152C1    pop         ebp
 006152C2    ret
*}
end;

//00615540
procedure sub_00615540(?:TWPMSiteMap; ?:AnsiString);
begin
{*
 00615540    push        esi
 00615541    push        edi
 00615542    mov         edi,edx
 00615544    mov         esi,eax
 00615546    mov         edx,edi
 00615548    mov         eax,dword ptr [esi+4]
 0061554B    mov         ecx,dword ptr [eax]
 0061554D    call        dword ptr [ecx+74]
 00615550    pop         edi
 00615551    pop         esi
 00615552    ret
*}
end;

end.